
Due to MODULEPATH changes, the following have been reloaded:
  1) fftw/3.3.10     2) py3-mpi4py/3.1.3     3) py3-scipy/1.5.4

python3: can't open file '../knn_digits_parallel_cluster_CORRECTED.py': [Errno 2] No such file or directory
